# Generated by Django 3.2.7 on 2021-10-02 02:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userchat',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='userchat',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='userchat',
            name='sender',
        ),
        migrations.AddField(
            model_name='userchat',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
